export type TranslationKey =
  | "localAuthenticator"
  | "newAccount"
  | "configuredAccounts"
  | "chooseAccount"
  | "account"
  | "accounts"
  | "noAccounts"
  | "emptyDescription"
  | "addFirstAccount"
  | "codesExpire"
  | "currentCode"
  | "expiresIn"
  | "copyCode"
  | "editAccount"
  | "deleteAccount"
  | "deleteConfirmation"
  | "accountDeleted"
  | "invalidSecret"
  | "error"
  | "addAccountEyebrow"
  | "editAccountEyebrow"
  | "addToVault"
  | "updateAccount"
  | "saveAccount"
  | "saveChanges"
  | "close"
  | "visibleName"
  | "service"
  | "userOrEmail"
  | "secretKey"
  | "namePlaceholder"
  | "servicePlaceholder"
  | "emailPlaceholder"
  | "secretPlaceholder"
  | "secretHelp"
  | "localStorageNote"
  | "cancel"
  | "showSecret"
  | "hideSecret"
  | "codeCopied"
  | "accountSaved"
  | "accountUpdated"
  | "updatingTo";

type TranslationValues = Record<TranslationKey, string>;

const English: TranslationValues = {
  localAuthenticator: "Local authenticator", newAccount: "New account", configuredAccounts: "Configured accounts", chooseAccount: "Choose an account to copy the code", account: "account", accounts: "accounts", noAccounts: "No accounts added", emptyDescription: "Add a TOTP key to generate and copy your codes here", addFirstAccount: "Add first account", codesExpire: "Codes expire every 30 seconds", currentCode: "CURRENT CODE", expiresIn: "Expires in {seconds}s", copyCode: "Copy code", editAccount: "Edit account", deleteAccount: "Delete account", deleteConfirmation: "Delete the account \"{name}\"?", accountDeleted: "{name} was deleted", invalidSecret: "Invalid key", error: "ERROR", addAccountEyebrow: "NEW ACCOUNT", editAccountEyebrow: "EDIT ACCOUNT", addToVault: "Add to vault", updateAccount: "Update details", saveAccount: "Save account", saveChanges: "Save changes", close: "Close", visibleName: "Display name", service: "Service", userOrEmail: "User or email", secretKey: "TOTP Base32 secret key", namePlaceholder: "E.g. Oracle - Main", servicePlaceholder: "E.g. Oracle", emailPlaceholder: "E.g. name@email.com", secretPlaceholder: "Paste your manual key here", secretHelp: "You can find it as \"manual entry key\", \"setup key\" or \"secret key\"", localStorageNote: "For this test version, the account is saved locally on this computer", cancel: "Cancel", showSecret: "Show secret key", hideSecret: "Hide secret key", codeCopied: "Code for {name} copied", accountSaved: "{name} was added", accountUpdated: "{name} was updated", updatingTo: "Updating to version {version}",
};

const Translations: Record<string, Partial<TranslationValues>> = {
  "pt-BR": { localAuthenticator: "Autenticador local", newAccount: "Nova conta", configuredAccounts: "CONTAS CONFIGURADAS", chooseAccount: "Escolha uma conta para copiar o código", account: "conta", accounts: "contas", noAccounts: "Nenhuma conta adicionada", emptyDescription: "Cadastre uma chave TOTP para gerar e copiar seus códigos daqui", addFirstAccount: "Adicionar primeira conta", codesExpire: "Os códigos expiram a cada 30 segundos", currentCode: "CÓDIGO ATUAL", expiresIn: "Expira em {seconds}s", copyCode: "Copiar código", editAccount: "Editar conta", deleteAccount: "Excluir conta", deleteConfirmation: "Excluir a conta \"{name}\"?", accountDeleted: "{name} foi excluída", invalidSecret: "Chave inválida", error: "ERRO", addAccountEyebrow: "NOVA CONTA", editAccountEyebrow: "EDITAR CONTA", addToVault: "Adicionar ao cofre", updateAccount: "Atualizar dados", saveAccount: "Salvar conta", saveChanges: "Salvar alterações", close: "Fechar", visibleName: "Nome visível", service: "Serviço", userOrEmail: "Usuário ou e-mail", secretKey: "Chave secreta TOTP Base32", namePlaceholder: "Ex.: Oracle - Principal", servicePlaceholder: "Ex.: Oracle", emailPlaceholder: "Ex.: nome@email.com", secretPlaceholder: "Cole sua chave manual aqui", secretHelp: "Você encontra essa chave em \"manual entry key\", \"setup key\" ou \"secret key\"", localStorageNote: "Para esta versão de teste, a conta é salva localmente neste computador", cancel: "Cancelar", showSecret: "Mostrar chave secreta", hideSecret: "Ocultar chave secreta", codeCopied: "Código de {name} copiado", accountSaved: "{name} foi adicionada", accountUpdated: "{name} foi atualizada", updatingTo: "Atualizando para a versão {version}" },
  es: { localAuthenticator: "Autenticador local", newAccount: "Nueva cuenta", configuredAccounts: "CUENTAS CONFIGURADAS", chooseAccount: "Elige una cuenta para copiar el código", account: "cuenta", accounts: "cuentas", noAccounts: "No hay cuentas añadidas", emptyDescription: "Añade una clave TOTP para generar y copiar tus códigos aquí", addFirstAccount: "Añadir primera cuenta", codesExpire: "Los códigos caducan cada 30 segundos", currentCode: "CÓDIGO ACTUAL", expiresIn: "Caduca en {seconds}s", copyCode: "Copiar código", editAccount: "Editar cuenta", deleteAccount: "Eliminar cuenta", deleteConfirmation: "¿Eliminar la cuenta \"{name}\"?", accountDeleted: "{name} fue eliminada", invalidSecret: "Clave no válida", error: "ERROR", addAccountEyebrow: "NUEVA CUENTA", editAccountEyebrow: "EDITAR CUENTA", addToVault: "Añadir a la bóveda", updateAccount: "Actualizar datos", saveAccount: "Guardar cuenta", saveChanges: "Guardar cambios", close: "Cerrar", visibleName: "Nombre visible", service: "Servicio", userOrEmail: "Usuario o correo", secretKey: "Clave secreta TOTP Base32", namePlaceholder: "Ej.: Oracle - Principal", servicePlaceholder: "Ej.: Oracle", emailPlaceholder: "Ej.: nombre@email.com", secretPlaceholder: "Pega tu clave manual aquí", secretHelp: "Puedes encontrarla como \"manual entry key\", \"setup key\" o \"secret key\"", localStorageNote: "En esta versión de prueba, la cuenta se guarda localmente en este equipo", cancel: "Cancelar", showSecret: "Mostrar clave secreta", hideSecret: "Ocultar clave secreta", codeCopied: "Código de {name} copiado", accountSaved: "{name} fue añadida", accountUpdated: "{name} fue actualizada", updatingTo: "Actualizando a la versión {version}" },
  fr: { localAuthenticator: "Authentificateur local", newAccount: "Nouveau compte", configuredAccounts: "COMPTES CONFIGURÉS", chooseAccount: "Choisissez un compte pour copier le code", account: "compte", accounts: "comptes", noAccounts: "Aucun compte ajouté", emptyDescription: "Ajoutez une clé TOTP pour générer et copier vos codes ici", addFirstAccount: "Ajouter un compte", codesExpire: "Les codes expirent toutes les 30 secondes", currentCode: "CODE ACTUEL", expiresIn: "Expire dans {seconds}s", copyCode: "Copier le code", editAccount: "Modifier le compte", deleteAccount: "Supprimer le compte", deleteConfirmation: "Supprimer le compte \"{name}\" ?", accountDeleted: "{name} a été supprimé", invalidSecret: "Clé non valide", error: "ERREUR", addAccountEyebrow: "NOUVEAU COMPTE", editAccountEyebrow: "MODIFIER LE COMPTE", addToVault: "Ajouter au coffre", updateAccount: "Mettre à jour", saveAccount: "Enregistrer le compte", saveChanges: "Enregistrer", close: "Fermer", visibleName: "Nom affiché", service: "Service", userOrEmail: "Utilisateur ou e-mail", secretKey: "Clé secrète TOTP Base32", namePlaceholder: "Ex. : Oracle - Principal", servicePlaceholder: "Ex. : Oracle", emailPlaceholder: "Ex. : nom@email.com", secretPlaceholder: "Collez votre clé ici", secretHelp: "Vous la trouverez sous \"manual entry key\", \"setup key\" ou \"secret key\"", localStorageNote: "Dans cette version de test, le compte est enregistré localement sur cet ordinateur", cancel: "Annuler", showSecret: "Afficher la clé secrète", hideSecret: "Masquer la clé secrète", codeCopied: "Code de {name} copié", accountSaved: "{name} a été ajouté", accountUpdated: "{name} a été mis à jour", updatingTo: "Mise à jour vers la version {version}" },
  de: { localAuthenticator: "Lokaler Authenticator", newAccount: "Neues Konto", configuredAccounts: "KONFIGURIERTE KONTEN", chooseAccount: "Wähle ein Konto zum Kopieren des Codes", account: "Konto", accounts: "Konten", noAccounts: "Keine Konten hinzugefügt", emptyDescription: "Füge einen TOTP-Schlüssel hinzu, um Codes hier zu erzeugen und zu kopieren", addFirstAccount: "Erstes Konto hinzufügen", codesExpire: "Codes laufen alle 30 Sekunden ab", currentCode: "AKTUELLER CODE", expiresIn: "Läuft in {seconds}s ab", copyCode: "Code kopieren", editAccount: "Konto bearbeiten", deleteAccount: "Konto löschen", deleteConfirmation: "Konto \"{name}\" löschen?", accountDeleted: "{name} wurde gelöscht", invalidSecret: "Ungültiger Schlüssel", error: "FEHLER", addAccountEyebrow: "NEUES KONTO", editAccountEyebrow: "KONTO BEARBEITEN", addToVault: "Zum Tresor hinzufügen", updateAccount: "Daten aktualisieren", saveAccount: "Konto speichern", saveChanges: "Änderungen speichern", close: "Schließen", visibleName: "Anzeigename", service: "Dienst", userOrEmail: "Benutzer oder E-Mail", secretKey: "Geheimer TOTP-Base32-Schlüssel", namePlaceholder: "z. B. Oracle - Hauptkonto", servicePlaceholder: "z. B. Oracle", emailPlaceholder: "z. B. name@email.com", secretPlaceholder: "Manuellen Schlüssel hier einfügen", secretHelp: "Du findest ihn als \"manual entry key\", \"setup key\" oder \"secret key\"", localStorageNote: "In dieser Testversion wird das Konto lokal auf diesem Computer gespeichert", cancel: "Abbrechen", showSecret: "Geheimen Schlüssel anzeigen", hideSecret: "Geheimen Schlüssel verbergen", codeCopied: "Code für {name} kopiert", accountSaved: "{name} wurde hinzugefügt", accountUpdated: "{name} wurde aktualisiert", updatingTo: "Aktualisierung auf Version {version}" },
  it: { localAuthenticator: "Autenticatore locale", newAccount: "Nuovo account", configuredAccounts: "ACCOUNT CONFIGURATI", chooseAccount: "Scegli un account per copiare il codice", account: "account", accounts: "account", noAccounts: "Nessun account aggiunto", emptyDescription: "Aggiungi una chiave TOTP per generare e copiare i tuoi codici qui", addFirstAccount: "Aggiungi il primo account", codesExpire: "I codici scadono ogni 30 secondi", currentCode: "CODICE ATTUALE", expiresIn: "Scade tra {seconds}s", copyCode: "Copia codice", editAccount: "Modifica account", deleteAccount: "Elimina account", deleteConfirmation: "Eliminare l'account \"{name}\"?", accountDeleted: "{name} è stato eliminato", invalidSecret: "Chiave non valida", error: "ERRORE", addAccountEyebrow: "NUOVO ACCOUNT", editAccountEyebrow: "MODIFICA ACCOUNT", addToVault: "Aggiungi al vault", updateAccount: "Aggiorna dati", saveAccount: "Salva account", saveChanges: "Salva modifiche", close: "Chiudi", visibleName: "Nome visualizzato", service: "Servizio", userOrEmail: "Utente o e-mail", secretKey: "Chiave segreta TOTP Base32", namePlaceholder: "Es.: Oracle - Principale", servicePlaceholder: "Es.: Oracle", emailPlaceholder: "Es.: nome@email.com", secretPlaceholder: "Incolla qui la chiave manuale", secretHelp: "Puoi trovarla come \"manual entry key\", \"setup key\" o \"secret key\"", localStorageNote: "In questa versione di test, l'account viene salvato localmente su questo computer", cancel: "Annulla", showSecret: "Mostra chiave segreta", hideSecret: "Nascondi chiave segreta", codeCopied: "Codice di {name} copiato", accountSaved: "{name} è stato aggiunto", accountUpdated: "{name} è stato aggiornato", updatingTo: "Aggiornamento alla versione {version}" },
  pl: { localAuthenticator: "Lokalny uwierzytelniacz", newAccount: "Nowe konto", configuredAccounts: "SKONFIGUROWANE KONTA", chooseAccount: "Wybierz konto, aby skopiować kod", account: "konto", accounts: "kont", noAccounts: "Nie dodano kont", emptyDescription: "Dodaj klucz TOTP, aby generować i kopiować kody tutaj", addFirstAccount: "Dodaj pierwsze konto", codesExpire: "Kody wygasają co 30 sekund", currentCode: "AKTUALNY KOD", expiresIn: "Wygasa za {seconds}s", copyCode: "Kopiuj kod", editAccount: "Edytuj konto", deleteAccount: "Usuń konto", deleteConfirmation: "Usunąć konto \"{name}\"?", accountDeleted: "Usunięto {name}", invalidSecret: "Nieprawidłowy klucz", error: "BŁĄD", addAccountEyebrow: "NOWE KONTO", editAccountEyebrow: "EDYTUJ KONTO", addToVault: "Dodaj do sejfu", updateAccount: "Aktualizuj dane", saveAccount: "Zapisz konto", saveChanges: "Zapisz zmiany", close: "Zamknij", visibleName: "Widoczna nazwa", service: "Usługa", userOrEmail: "Użytkownik lub e-mail", secretKey: "Tajny klucz TOTP Base32", namePlaceholder: "Np. Oracle - Główne", servicePlaceholder: "Np. Oracle", emailPlaceholder: "Np. nazwa@email.com", secretPlaceholder: "Wklej klucz ręczny tutaj", secretHelp: "Znajdziesz go jako \"manual entry key\", \"setup key\" lub \"secret key\"", localStorageNote: "W tej wersji testowej konto jest zapisane lokalnie na tym komputerze", cancel: "Anuluj", showSecret: "Pokaż tajny klucz", hideSecret: "Ukryj tajny klucz", codeCopied: "Kod dla {name} skopiowano", accountSaved: "Dodano {name}", accountUpdated: "Zaktualizowano {name}", updatingTo: "Aktualizacja do wersji {version}" },
  ru: { localAuthenticator: "Локальный аутентификатор", newAccount: "Новый аккаунт", configuredAccounts: "НАСТРОЕННЫЕ АККАУНТЫ", chooseAccount: "Выберите аккаунт, чтобы скопировать код", account: "аккаунт", accounts: "аккаунтов", noAccounts: "Нет добавленных аккаунтов", emptyDescription: "Добавьте ключ TOTP, чтобы создавать и копировать коды здесь", addFirstAccount: "Добавить первый аккаунт", codesExpire: "Коды истекают каждые 30 секунд", currentCode: "ТЕКУЩИЙ КОД", expiresIn: "Истекает через {seconds} с", copyCode: "Копировать код", editAccount: "Изменить аккаунт", deleteAccount: "Удалить аккаунт", deleteConfirmation: "Удалить аккаунт \"{name}\"?", accountDeleted: "{name} удалён", invalidSecret: "Неверный ключ", error: "ОШИБКА", addAccountEyebrow: "НОВЫЙ АККАУНТ", editAccountEyebrow: "ИЗМЕНИТЬ АККАУНТ", addToVault: "Добавить в хранилище", updateAccount: "Обновить данные", saveAccount: "Сохранить аккаунт", saveChanges: "Сохранить изменения", close: "Закрыть", visibleName: "Отображаемое имя", service: "Сервис", userOrEmail: "Пользователь или e-mail", secretKey: "Секретный ключ TOTP Base32", namePlaceholder: "Напр.: Oracle - Основной", servicePlaceholder: "Напр.: Oracle", emailPlaceholder: "Напр.: name@email.com", secretPlaceholder: "Вставьте ключ вручную", secretHelp: "Вы найдёте его как \"manual entry key\", \"setup key\" или \"secret key\"", localStorageNote: "В этой тестовой версии аккаунт хранится локально на этом компьютере", cancel: "Отмена", showSecret: "Показать секретный ключ", hideSecret: "Скрыть секретный ключ", codeCopied: "Код для {name} скопирован", accountSaved: "{name} добавлен", accountUpdated: "{name} обновлён", updatingTo: "Обновление до версии {version}" },
  uk: { localAuthenticator: "Локальний автентифікатор", newAccount: "Новий обліковий запис", configuredAccounts: "НАЛАШТОВАНІ ОБЛІКОВІ ЗАПИСИ", chooseAccount: "Виберіть обліковий запис, щоб скопіювати код", account: "обліковий запис", accounts: "облікових записів", noAccounts: "Немає доданих облікових записів", emptyDescription: "Додайте ключ TOTP, щоб створювати та копіювати коди тут", addFirstAccount: "Додати перший обліковий запис", codesExpire: "Коди спливають кожні 30 секунд", currentCode: "ПОТОЧНИЙ КОД", expiresIn: "Спливає через {seconds} с", copyCode: "Копіювати код", editAccount: "Редагувати обліковий запис", deleteAccount: "Видалити обліковий запис", deleteConfirmation: "Видалити обліковий запис \"{name}\"?", accountDeleted: "{name} видалено", invalidSecret: "Недійсний ключ", error: "ПОМИЛКА", addAccountEyebrow: "НОВИЙ ОБЛІКОВИЙ ЗАПИС", editAccountEyebrow: "РЕДАГУВАТИ ОБЛІКОВИЙ ЗАПИС", addToVault: "Додати до сховища", updateAccount: "Оновити дані", saveAccount: "Зберегти", saveChanges: "Зберегти зміни", close: "Закрити", visibleName: "Відображуване ім’я", service: "Сервіс", userOrEmail: "Користувач або e-mail", secretKey: "Секретний ключ TOTP Base32", namePlaceholder: "Напр.: Oracle - Основний", servicePlaceholder: "Напр.: Oracle", emailPlaceholder: "Напр.: name@email.com", secretPlaceholder: "Вставте ключ вручну", secretHelp: "Його можна знайти як \"manual entry key\", \"setup key\" або \"secret key\"", localStorageNote: "У цій тестовій версії обліковий запис зберігається локально на цьому комп’ютері", cancel: "Скасувати", showSecret: "Показати секретний ключ", hideSecret: "Приховати секретний ключ", codeCopied: "Код для {name} скопійовано", accountSaved: "{name} додано", accountUpdated: "{name} оновлено", updatingTo: "Оновлення до версії {version}" },
  tr: { localAuthenticator: "Yerel doğrulayıcı", newAccount: "Yeni hesap", configuredAccounts: "YAPILANDIRILMIŞ HESAPLAR", chooseAccount: "Kodu kopyalamak için bir hesap seçin", account: "hesap", accounts: "hesap", noAccounts: "Hesap eklenmedi", emptyDescription: "Kodlarınızı burada oluşturmak ve kopyalamak için bir TOTP anahtarı ekleyin", addFirstAccount: "İlk hesabı ekle", codesExpire: "Kodların süresi her 30 saniyede dolar", currentCode: "GEÇERLİ KOD", expiresIn: "{seconds} sn içinde dolar", copyCode: "Kodu kopyala", editAccount: "Hesabı düzenle", deleteAccount: "Hesabı sil", deleteConfirmation: "\"{name}\" hesabı silinsin mi?", accountDeleted: "{name} silindi", invalidSecret: "Geçersiz anahtar", error: "HATA", addAccountEyebrow: "YENİ HESAP", editAccountEyebrow: "HESABI DÜZENLE", addToVault: "Kasaya ekle", updateAccount: "Bilgileri güncelle", saveAccount: "Hesabı kaydet", saveChanges: "Değişiklikleri kaydet", close: "Kapat", visibleName: "Görünen ad", service: "Hizmet", userOrEmail: "Kullanıcı veya e-posta", secretKey: "TOTP Base32 gizli anahtarı", namePlaceholder: "Örn.: Oracle - Ana", servicePlaceholder: "Örn.: Oracle", emailPlaceholder: "Örn.: ad@email.com", secretPlaceholder: "Manuel anahtarı buraya yapıştırın", secretHelp: "\"manual entry key\", \"setup key\" veya \"secret key\" olarak bulabilirsiniz", localStorageNote: "Bu test sürümünde hesap bu bilgisayarda yerel olarak kaydedilir", cancel: "İptal", showSecret: "Gizli anahtarı göster", hideSecret: "Gizli anahtarı gizle", codeCopied: "{name} kodu kopyalandı", accountSaved: "{name} eklendi", accountUpdated: "{name} güncellendi", updatingTo: "{version} sürümüne güncelleniyor" },
  ar: { localAuthenticator: "مُصادِق محلي", newAccount: "حساب جديد", configuredAccounts: "الحسابات المُعَدَّة", chooseAccount: "اختر حساباً لنسخ الرمز", account: "حساب", accounts: "حسابات", noAccounts: "لم تتم إضافة حسابات", emptyDescription: "أضف مفتاح TOTP لإنشاء رموزك ونسخها هنا", addFirstAccount: "إضافة الحساب الأول", codesExpire: "تنتهي صلاحية الرموز كل 30 ثانية", currentCode: "الرمز الحالي", expiresIn: "تنتهي خلال {seconds}ث", copyCode: "نسخ الرمز", editAccount: "تعديل الحساب", deleteAccount: "حذف الحساب", deleteConfirmation: "حذف الحساب \"{name}\"؟", accountDeleted: "تم حذف {name}", invalidSecret: "مفتاح غير صالح", error: "خطأ", addAccountEyebrow: "حساب جديد", editAccountEyebrow: "تعديل الحساب", addToVault: "إضافة إلى الخزنة", updateAccount: "تحديث البيانات", saveAccount: "حفظ الحساب", saveChanges: "حفظ التغييرات", close: "إغلاق", visibleName: "الاسم الظاهر", service: "الخدمة", userOrEmail: "المستخدم أو البريد الإلكتروني", secretKey: "مفتاح TOTP Base32 السري", namePlaceholder: "مثال: Oracle - الرئيسي", servicePlaceholder: "مثال: Oracle", emailPlaceholder: "مثال: name@email.com", secretPlaceholder: "الصق المفتاح اليدوي هنا", secretHelp: "قد تجده باسم \"manual entry key\" أو \"setup key\" أو \"secret key\"", localStorageNote: "في هذه النسخة التجريبية، يُحفظ الحساب محلياً على هذا الكمبيوتر", cancel: "إلغاء", showSecret: "إظهار المفتاح السري", hideSecret: "إخفاء المفتاح السري", codeCopied: "تم نسخ رمز {name}", accountSaved: "تمت إضافة {name}", accountUpdated: "تم تحديث {name}", updatingTo: "جارٍ التحديث إلى الإصدار {version}" },
  ja: { localAuthenticator: "ローカル認証アプリ", newAccount: "新しいアカウント", configuredAccounts: "設定済みアカウント", chooseAccount: "コードをコピーするアカウントを選択", account: "アカウント", accounts: "アカウント", noAccounts: "アカウントが追加されていません", emptyDescription: "TOTP キーを追加して、ここでコードを生成・コピーできます", addFirstAccount: "最初のアカウントを追加", codesExpire: "コードは30秒ごとに期限切れになります", currentCode: "現在のコード", expiresIn: "残り {seconds} 秒", copyCode: "コードをコピー", editAccount: "アカウントを編集", deleteAccount: "アカウントを削除", deleteConfirmation: "アカウント \"{name}\" を削除しますか？", accountDeleted: "{name} を削除しました", invalidSecret: "無効なキー", error: "エラー", addAccountEyebrow: "新しいアカウント", editAccountEyebrow: "アカウントを編集", addToVault: "保管庫に追加", updateAccount: "詳細を更新", saveAccount: "アカウントを保存", saveChanges: "変更を保存", close: "閉じる", visibleName: "表示名", service: "サービス", userOrEmail: "ユーザーまたはメール", secretKey: "TOTP Base32 シークレットキー", namePlaceholder: "例: Oracle - メイン", servicePlaceholder: "例: Oracle", emailPlaceholder: "例: name@email.com", secretPlaceholder: "手動キーをここに貼り付け", secretHelp: "\"manual entry key\"、\"setup key\"、\"secret key\" として見つかります", localStorageNote: "このテスト版では、アカウントはこのコンピューターにローカル保存されます", cancel: "キャンセル", showSecret: "シークレットキーを表示", hideSecret: "シークレットキーを隠す", codeCopied: "{name} のコードをコピーしました", accountSaved: "{name} を追加しました", accountUpdated: "{name} を更新しました", updatingTo: "バージョン {version} に更新中" },
  ko: { localAuthenticator: "로컬 인증기", newAccount: "새 계정", configuredAccounts: "구성된 계정", chooseAccount: "코드를 복사할 계정을 선택하세요", account: "계정", accounts: "계정", noAccounts: "추가된 계정이 없습니다", emptyDescription: "TOTP 키를 추가하여 여기에서 코드를 만들고 복사하세요", addFirstAccount: "첫 계정 추가", codesExpire: "코드는 30초마다 만료됩니다", currentCode: "현재 코드", expiresIn: "{seconds}초 후 만료", copyCode: "코드 복사", editAccount: "계정 수정", deleteAccount: "계정 삭제", deleteConfirmation: "\"{name}\" 계정을 삭제할까요?", accountDeleted: "{name} 계정이 삭제되었습니다", invalidSecret: "잘못된 키", error: "오류", addAccountEyebrow: "새 계정", editAccountEyebrow: "계정 수정", addToVault: "보관함에 추가", updateAccount: "정보 업데이트", saveAccount: "계정 저장", saveChanges: "변경 사항 저장", close: "닫기", visibleName: "표시 이름", service: "서비스", userOrEmail: "사용자 또는 이메일", secretKey: "TOTP Base32 비밀 키", namePlaceholder: "예: Oracle - 기본", servicePlaceholder: "예: Oracle", emailPlaceholder: "예: name@email.com", secretPlaceholder: "수동 키를 여기에 붙여넣기", secretHelp: "\"manual entry key\", \"setup key\", \"secret key\"로 찾을 수 있습니다", localStorageNote: "이 테스트 버전에서는 계정이 이 컴퓨터에 로컬로 저장됩니다", cancel: "취소", showSecret: "비밀 키 표시", hideSecret: "비밀 키 숨기기", codeCopied: "{name} 코드가 복사되었습니다", accountSaved: "{name} 계정이 추가되었습니다", accountUpdated: "{name} 계정이 업데이트되었습니다", updatingTo: "버전 {version}으로 업데이트 중" },
  "zh-CN": { localAuthenticator: "本地身份验证器", newAccount: "新账户", configuredAccounts: "已配置账户", chooseAccount: "选择一个账户以复制代码", account: "个账户", accounts: "个账户", noAccounts: "尚未添加账户", emptyDescription: "添加 TOTP 密钥以在此生成和复制代码", addFirstAccount: "添加第一个账户", codesExpire: "代码每 30 秒过期", currentCode: "当前代码", expiresIn: "{seconds} 秒后过期", copyCode: "复制代码", editAccount: "编辑账户", deleteAccount: "删除账户", deleteConfirmation: "删除账户 \"{name}\"？", accountDeleted: "已删除 {name}", invalidSecret: "密钥无效", error: "错误", addAccountEyebrow: "新账户", editAccountEyebrow: "编辑账户", addToVault: "添加到保管库", updateAccount: "更新资料", saveAccount: "保存账户", saveChanges: "保存更改", close: "关闭", visibleName: "显示名称", service: "服务", userOrEmail: "用户名或邮箱", secretKey: "TOTP Base32 密钥", namePlaceholder: "例如：Oracle - 主账户", servicePlaceholder: "例如：Oracle", emailPlaceholder: "例如：name@email.com", secretPlaceholder: "在此粘贴手动密钥", secretHelp: "可在 \"manual entry key\"、\"setup key\" 或 \"secret key\" 中找到", localStorageNote: "在此测试版本中，账户会保存在这台电脑本地", cancel: "取消", showSecret: "显示密钥", hideSecret: "隐藏密钥", codeCopied: "已复制 {name} 的代码", accountSaved: "已添加 {name}", accountUpdated: "已更新 {name}", updatingTo: "正在更新到版本 {version}" },
  "zh-TW": { localAuthenticator: "本機驗證器", newAccount: "新增帳戶", configuredAccounts: "已設定帳戶", chooseAccount: "選擇帳戶以複製代碼", account: "個帳戶", accounts: "個帳戶", noAccounts: "尚未新增帳戶", emptyDescription: "新增 TOTP 金鑰以在此產生及複製代碼", addFirstAccount: "新增第一個帳戶", codesExpire: "代碼每 30 秒到期", currentCode: "目前代碼", expiresIn: "{seconds} 秒後到期", copyCode: "複製代碼", editAccount: "編輯帳戶", deleteAccount: "刪除帳戶", deleteConfirmation: "刪除帳戶 \"{name}\"？", accountDeleted: "已刪除 {name}", invalidSecret: "金鑰無效", error: "錯誤", addAccountEyebrow: "新增帳戶", editAccountEyebrow: "編輯帳戶", addToVault: "加入保管庫", updateAccount: "更新資料", saveAccount: "儲存帳戶", saveChanges: "儲存變更", close: "關閉", visibleName: "顯示名稱", service: "服務", userOrEmail: "使用者或電子郵件", secretKey: "TOTP Base32 密鑰", namePlaceholder: "例如：Oracle - 主要", servicePlaceholder: "例如：Oracle", emailPlaceholder: "例如：name@email.com", secretPlaceholder: "在此貼上手動金鑰", secretHelp: "可在 \"manual entry key\"、\"setup key\" 或 \"secret key\" 中找到", localStorageNote: "在此測試版中，帳戶會儲存在這台電腦本機", cancel: "取消", showSecret: "顯示密鑰", hideSecret: "隱藏密鑰", codeCopied: "已複製 {name} 的代碼", accountSaved: "已新增 {name}", accountUpdated: "已更新 {name}", updatingTo: "正在更新至版本 {version}" },
  hi: { localAuthenticator: "स्थानीय प्रमाणक", newAccount: "नया खाता", configuredAccounts: "कॉन्फ़िगर किए गए खाते", chooseAccount: "कोड कॉपी करने के लिए एक खाता चुनें", account: "खाता", accounts: "खाते", noAccounts: "कोई खाता नहीं जोड़ा गया", emptyDescription: "यहाँ कोड बनाने और कॉपी करने के लिए TOTP कुंजी जोड़ें", addFirstAccount: "पहला खाता जोड़ें", codesExpire: "कोड हर 30 सेकंड में समाप्त होते हैं", currentCode: "वर्तमान कोड", expiresIn: "{seconds} सेकंड में समाप्त", copyCode: "कोड कॉपी करें", editAccount: "खाता संपादित करें", deleteAccount: "खाता हटाएँ", deleteConfirmation: "खाता \"{name}\" हटाएँ?", accountDeleted: "{name} हटा दिया गया", invalidSecret: "अमान्य कुंजी", error: "त्रुटि", addAccountEyebrow: "नया खाता", editAccountEyebrow: "खाता संपादित करें", addToVault: "वॉल्ट में जोड़ें", updateAccount: "विवरण अपडेट करें", saveAccount: "खाता सहेजें", saveChanges: "बदलाव सहेजें", close: "बंद करें", visibleName: "दिखने वाला नाम", service: "सेवा", userOrEmail: "उपयोगकर्ता या ईमेल", secretKey: "TOTP Base32 गुप्त कुंजी", namePlaceholder: "जैसे: Oracle - मुख्य", servicePlaceholder: "जैसे: Oracle", emailPlaceholder: "जैसे: name@email.com", secretPlaceholder: "मैन्युअल कुंजी यहाँ पेस्ट करें", secretHelp: "यह \"manual entry key\", \"setup key\" या \"secret key\" के रूप में मिलती है", localStorageNote: "इस परीक्षण संस्करण में खाता इस कंप्यूटर पर स्थानीय रूप से सहेजा जाता है", cancel: "रद्द करें", showSecret: "गुप्त कुंजी दिखाएँ", hideSecret: "गुप्त कुंजी छिपाएँ", codeCopied: "{name} का कोड कॉपी किया गया", accountSaved: "{name} जोड़ा गया", accountUpdated: "{name} अपडेट किया गया", updatingTo: "संस्करण {version} में अपडेट हो रहा है" },
  id: { localAuthenticator: "Autentikator lokal", newAccount: "Akun baru", configuredAccounts: "AKUN YANG DIKONFIGURASI", chooseAccount: "Pilih akun untuk menyalin kode", account: "akun", accounts: "akun", noAccounts: "Belum ada akun ditambahkan", emptyDescription: "Tambahkan kunci TOTP untuk membuat dan menyalin kode di sini", addFirstAccount: "Tambahkan akun pertama", codesExpire: "Kode kedaluwarsa setiap 30 detik", currentCode: "KODE SAAT INI", expiresIn: "Berakhir dalam {seconds}d", copyCode: "Salin kode", editAccount: "Edit akun", deleteAccount: "Hapus akun", deleteConfirmation: "Hapus akun \"{name}\"?", accountDeleted: "{name} telah dihapus", invalidSecret: "Kunci tidak valid", error: "KESALAHAN", addAccountEyebrow: "AKUN BARU", editAccountEyebrow: "EDIT AKUN", addToVault: "Tambahkan ke brankas", updateAccount: "Perbarui data", saveAccount: "Simpan akun", saveChanges: "Simpan perubahan", close: "Tutup", visibleName: "Nama tampilan", service: "Layanan", userOrEmail: "Pengguna atau email", secretKey: "Kunci rahasia TOTP Base32", namePlaceholder: "Contoh: Oracle - Utama", servicePlaceholder: "Contoh: Oracle", emailPlaceholder: "Contoh: name@email.com", secretPlaceholder: "Tempel kunci manual di sini", secretHelp: "Anda dapat menemukannya sebagai \"manual entry key\", \"setup key\", atau \"secret key\"", localStorageNote: "Dalam versi uji ini, akun disimpan secara lokal di komputer ini", cancel: "Batal", showSecret: "Tampilkan kunci rahasia", hideSecret: "Sembunyikan kunci rahasia", codeCopied: "Kode {name} disalin", accountSaved: "{name} ditambahkan", accountUpdated: "{name} diperbarui", updatingTo: "Memperbarui ke versi {version}" },
};

function GetPreferredLocale(): string {
  const PreferredLanguage = navigator.languages?.[0] ?? navigator.language ?? "en";
  const NormalizedLanguage = PreferredLanguage.replace("_", "-");
  if (Translations[NormalizedLanguage]) return NormalizedLanguage;
  if (NormalizedLanguage.startsWith("pt")) return "pt-BR";
  if (NormalizedLanguage.startsWith("zh-Hant")) return "zh-TW";
  if (NormalizedLanguage.startsWith("zh")) return "zh-CN";
  return NormalizedLanguage.split("-")[0] ?? "en";
}

export const CurrentLocale = GetPreferredLocale();
export const IsRightToLeft = CurrentLocale === "ar";

export function Translate(Key: TranslationKey, Values: Record<string, string | number> = {}): string {
  const Translation = Translations[CurrentLocale]?.[Key] ?? English[Key];
  return Translation.replace(/\{(\w+)\}/g, (_, Name: string) => String(Values[Name] ?? ""));
}
